# Generated by Django 5.2.5 on 2025-10-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounter',
            options={'ordering': ['-started_at'], 'verbose_name': 'Визит', 'verbose_name_plural': 'Визиты'},
        ),
        migrations.AlterField(
            model_name='encounter',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание визита'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина визита'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='started_at',
            field=models.DateTimeField(verbose_name='Начало визита'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Запланирован'), ('INPROGRESS', 'В процессе'), ('FINISHED', 'Завершен')], default='PLANNED', max_length=20, verbose_name='Статус'),
        ),
    ]
