# Generated by Django 5.2.5 on 2025-12-06 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_alter_encounter_options_alter_encounter_finished_at_and_more'),
        ('patients', '0007_alter_patient_patient_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('visit_created', 'Создан визит'), ('visit_closed', 'Закрыт визит'), ('note_add', 'Добавлена заметка'), ('rx_add', 'Назначение лекарства'), ('patient_update', 'Обновлена информация о пациенте'), ('facility_update', 'Обновлена информация о месте размещения')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='patients.patient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
