# Generated by Django 5.2.5 on 2026-03-06 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_patientinteraction'),
        ('patients', '0011_patient_callsign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinteraction',
            name='action',
            field=models.CharField(choices=[('visit_created', 'Создан визит'), ('visit_closed', 'Закрыт визит'), ('note_add', 'Добавлена заметка'), ('rx_add', 'Назначение лекарства'), ('patient_update', 'Обновлена информация о пациенте'), ('facility_update', 'Обновлена информация о месте размещения'), ('plan_item_add', 'Добавлен пункт плана'), ('plan_item_delete', 'Удалён пункт плана'), ('plan_item_toggle', 'Изменён статус пункта плана')], max_length=50),
        ),
        migrations.CreateModel(
            name='TreatmentPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Пункт по порядку')),
                ('event', models.CharField(max_length=500, verbose_name='Мероприятие')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Дата исполнения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plan', to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Пункт плана лечения',
                'verbose_name_plural': 'Планы лечения',
                'ordering': ['order'],
            },
        ),
    ]
