# Generated by Django 5.2.5 on 2026-03-07 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_alter_patientinteraction_action_treatmentplanitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='treatment_plan_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='clinical.treatmentplanitem', verbose_name='Пункт плана лечения'),
        ),
    ]
