# Generated by Django 5.2.5 on 2025-10-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('cardio', 'Кардиология'), ('therapy', 'Терапия'), ('neuro', 'Неврология'), ('psy', 'Психиатрия')], help_text='Обязательно для регистраторов, врачей и медсестер', max_length=20, null=True, verbose_name='Отделение'),
        ),
    ]
