# Generated by Django 5.2.5 on 2026-01-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('cardiology', 'Кардиология'), ('therapy', 'Терапия'), ('psychiatry', 'Психиатрия'), ('neurology', 'Неврология')], help_text='Обязательно для регистраторов, врачей и медсестер', max_length=20, null=True, verbose_name='Отделение'),
        ),
    ]
