# Generated by Django 5.2.10 on 2026-03-15 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('meeting', 'Совещание'), ('training', 'Обучение'), ('inspection', 'Проверка'), ('report', 'Отчёт'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип мероприятия')),
                ('event_date', models.DateField(verbose_name='Дата проведения')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('department', models.CharField(blank=True, choices=[('cardiology', 'Кардиология'), ('therapy', 'Терапия'), ('psychiatry', 'Психиатрия'), ('neurology', 'Неврология')], max_length=20, verbose_name='Отделение')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-event_date', '-event_time'],
            },
        ),
    ]
