# Generated by Django 5.2.5 on 2025-10-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='department',
            field=models.CharField(choices=[('cardio', 'Кардиология'), ('therapy', 'Терапия'), ('neuro', 'Неврология'), ('psy', 'Психиатрия')], default='therapy', max_length=20, verbose_name='Отделение'),
        ),
    ]
