# Generated by Django 5.2.5 on 2025-11-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.CharField(choices=[('cardiology', 'Кардиология'), ('therapy', 'Терапия'), ('psychiatry', 'Психиатрия'), ('neurology', 'Неврология')], default='therapy', max_length=20, verbose_name='Отделение'),
        ),
    ]
