# Generated by Django 5.2.5 on 2025-11-23 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(choices=[('hospital', 'Больница'), ('sanatorium', 'Санаторий'), ('daycare', 'Дневной стационар')], max_length=20, verbose_name='Тип учреждения')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Место размещения',
                'verbose_name_plural': 'Места размещения',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.facility', verbose_name='Место размещения'),
        ),
    ]
