# Generated by Django 5.2.5 on 2025-12-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_facility_patient_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('adult', 'Взрослый'), ('child', 'Ребёнок'), ('unknown', 'Неопределён')], default='adult', max_length=10, verbose_name='Тип пациента'),
        ),
    ]
