# Generated by Django 5.2.5 on 2026-01-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='employer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место работы'),
        ),
    ]
